dist: precise

language: php

php:
  - 7.3

addons:
  postgresql: "9.4"

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - psql -c 'create database testing;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --force

script:
  - vendor/bin/phpunit